org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.debug=false

neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.85
neo_version_range=[21.1.0,)
loader_version_range=[4,)

mod_id=observerlib
mod_name=ObserverLib
mod_license=GNU Lesser General Public License v3.0
mod_version=1.9.0
mod_group_id=hellfirepvp.observerlib
mod_authors=HellFirePvP
mod_description=Cached world structure and change monitoring library.
